## Exercise 3: Biography - 25 Marks

# Store information in variables
name = "Sadiya"
hometown = "Ajman"
age = 21

# Store the information in a dictionary
biography = {
    "Name": name,
    "Hometown": hometown,
    "Age": age
}

# Print all values on separate lines using ONE print statement
print(
    "=== Personal Profile ===\n"
    f"Name: {biography['Name']}\n"
    f"Hometown: {biography['Hometown']}\n"
    f"Age: {biography['Age']}"
)